### PR TITLE
fix: allow 0-width stroke width and 0-percent fill-opacity

### PR DESCRIPTION
**Pull request by PierreSchwang**
## Overview

Based on an issue on discord 
grafik

## Description
Now a 0-width stroke width and 0-percent fill-opacity is possible + code reformat 

## Submitter Checklist

- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] I tested my changes and approved their functionality.
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md)

## Maintainer checklist

Before the changes are marked as `Ready for merge`: 

- [ ] There are at least 2 approvals from project developers or maintainers for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional modification steps from users, e.g. for permission changes, make sure the entry is added to the pull request description so it can be appended to the changelog.

### CODE REVIEW

**Comment by PierreSchwang** [comment]
Regression I found out: Now the area is not clickable anymore, just the border, if the opacity is 0 no

**Review by NotMyFault — COMMENTED** [review]
My experience with Dynmap is limited. Is that something we can resolve on our end?

**Comment by PierreSchwang** [comment]
> My experience with Dynmap is limited. Is that something we can resolve on our end?

I've searched through dynmaps source as well, but I don't know either. I've created a separated issue as a feature request in dynmaps repo for that: https://github.com/webbukkit/dynmap/issues/3637

**Comment by PierreSchwang** [comment]
@NotMyFault Found a workaround by setting the color to #FF0000**00** when the opacity is set to 0. The opacity is then set back to 1 and an 0-alpha channel is passed to the fill color. therefor the fill is still being added to the dom, but it's invisible.

**Review by NotMyFault — APPROVED** [review]
Looks fine so far

**Pull request merged**
